### ISSUE TITLE
Delete payment method not supported using braintree.js

### ISSUE THREAD

**Issue by gregblass** [highfidelity/fake_braintree#101]
Getting "Braintree::UnexpectedError: expected a gzipped response" for:

    Braintree::PaymentMethod.delete()

**Comment by wacii** [comment]
`PaymentMethod.delete` is not supported but `CreditCard.delete` is.

**Comment by wacii** [comment]
Not sure why I didn't add this in the first place. Just a matter of copy-pasting the credit card delete function, so I went ahead and added it. Don't know when it'll be merged though.

**Comment by gregblass** [comment]
Thanks! I just changed my code to use CreditCard instead of PaymentMethod and was able to test it just fine that way. But as soon as it gets released I'll switch it back in efforts of code consistency. Thank you though!

**Comment by birarda** [comment]
Merged - will try and release a new version of gem later today
