### ISSUE TITLE
Plans to Support Braintree Marketplace?

### ISSUE THREAD

**Issue by rovermicrover** [highfidelity/fake_braintree#108]
Are there any plans to support [Braintree Market](https://www.braintreepayments.com/features/marketplace) place at any point?

**Comment by birarda** [comment]
Hey @rovermicrover - we're currently very lightly maintaining this gem (as you can tell from this delayed response) and aren't even able to use it in our current codebase. Braintree Marketplace support is not high priority.

Feel free to submit a PR if you can get it working!
