### ISSUE TITLE
Exception raised undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by beanieboi** [highfidelity/fake_braintree#111]
Hey,

first of all, thanks for maintaining fake_braintree. it helps us a ton.

we recently encountered a a strange problem where we try to parse the response from a transparent_redirect request. our JSON parsing failed and said that the response is not a valid JSON. it is very hard to reproduce but i finally got a log output. it not very much, but it's a start. i just want to put that out there, maybe other people are facing the same problem.

we are using rspec with parallel_tests and therefor running 6 fake braintree servers.

minor problems i faced so far:
- the log file get's overwritten, since multiple threads want to access the same file. maybe we can add a uniq identifier to the log file?
- all logging is disable, maybe add a debug option, it's really hard to get any output from fake_braintree to the surface.

the exception i see. sadly i don't have a stack trace yet nor which route is causing this.

```
Internal Server Error
undefined method `[]' for nil:NilClass


 WEBrick/1.3.1 (Ruby/2.2.3/2015-08-18) at
 localhost:39331
```

i will update the issue when i have more information.

**Comment by beanieboi** [comment]
hey.

i got some more stack trace. it looks like this is happening in rack-protection and not in fake_braintree.

```
NoMethodError at /merchants/xxx/transparent_redirect_requests
undefined method `[]' for nil:NilClass
file:
  base.rb
location: html?
line:
   117
/home/ubuntu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb in html?
```

i think we can close this one and i will investigate rack-protection.

**Comment by beanieboi** [comment]
hey,

i think i have to open this again. i debugged a little more and it seems that fake_braintree (maybe sinatra)  is sending a wrong header to rack-protection. i'm still clueless and continue debugging.

**Comment by beanieboi** [comment]
just copy & pasting the answer from the rack-protection issue.

@kytrinyx oh yeah, thanks! i forgot to close :)
it actually chased it down to the Bitbucket gem extending NilClass to respond to `content_type`

https://github.com/vongrippen/bitbucket/blob/master/lib/bitbucket_rest_api/result.rb#L21-L23
https://github.com/vongrippen/bitbucket/blob/master/lib/bitbucket_rest_api/response/helpers.rb#L8-L18

because of this, Sinatra enters the wrong branch of the `if` over here: https://github.com/sinatra/sinatra/blob/master/lib/sinatra/base.rb#L910-L914

`body[0]` is a NilClass and therefor does not set the content-type to HTML for a redirect.

we (read I :D) have to fix the Bitbucket gem to not patch NilClass.

cc
https://github.com/highfidelity/fake_braintree/issues/111

**Comment by beanieboi** [comment]
closing this since it was the bitbucket gem. it monkey patched NilClass and gave Sinatra a hard time with that.

https://wwesuperstartripleh.files.wordpress.com/2010/06/4.jpg

**Comment by birarda** [comment]
Thanks for the updates on this @beanieboi!

**Comment by beanieboi** [comment]
thanks for your patience. i used the PR as my rubber duck for debugging :)
