### ISSUE TITLE
Deactivating fake_braintree for specific tests

### ISSUE THREAD

**Issue by michaelcarter** [highfidelity/fake_braintree#27]
For the vast majority of our tests, we want to have fake braintree enabled in order to keep things quick. However, some of our tests need to get to braintree and test the sandbox. It'd be great if we could do something like:

```
FakeBraintree.disable!

# Test code

FakeBraintree.enable! 
```

Just to allow requests through as and when we need to. Is there a way to do this?

**Comment by Ewg777** [comment]
@gabebw is there more convenient method for now?
